### ISSUE TITLE
cudnn error

### ISSUE THREAD

**Issue by xiaopuLee** [arthurxlw/cytonMt#1]
hello,
  I've compiled sucessfully.
 however when I tried on my own data, cudnn error happened while cytonMt worked well with the data and script you provided.

cuDNN Error: CUDNN_STATUS_EXECUTION_FAILED src/cytonLib/CuDropoutLayer.cu 37
cytonMt: src/cytonLib/basicHeads.cu:52: cudnnStatus_t cytonLib::checkError_(cudnnStatus_t, const char*, int): Assertion `false' failed.

and 
    1   the embedding size and hidden size shares one parameter, this is different for me to try different sizes.
   2   is there a parameter for the deveceId ?

many thanks.

**Comment by arthurxlw** [comment]
1) cytonMt: src/cytonLib/basicHeads.cu:52: cudnnStatus_t cytonLib::checkError_(cudnnStatus_t, const char*, int): Assertion `false' failed.

The error is a run-time error.  Re-setting the cudnn library might solve the problem. 

2) We got no positive experimental results by using different sizes of embedding and hidden size. Maybe we should allow it  in order to be compatible with other tools. Thank you.

3) The code for setting deviceid is in Global.cu Global::init() cudaSetDevice(0);
Usually we do it by setting the environment variable export CUDA_VISIBLE_DEVICES=0,  export CUDA_VISIBLE_DEVICES=1, ...
